version: "3.8"

services:
  cassandra:
    image: cassandra:5
    container_name: cassandra-db
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=nestjs_cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - data-ingestion-network

  cassandra-web:
    image: instaclustr/cassandra-web:0.5.0
    container_name: cassandra-web
    environment:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
    ports:
      - "3001:3000"
    depends_on:
      cassandra:
        condition: service_healthy
    networks:
      - data-ingestion-network

volumes:
  cassandra_data:
